import math

FPS = 60

CAR_WIDTH = 30
CAR_HEIGHT = 15

SPAWN_X = 335
SPAWN_Y = 620

INITIAL_ANGLE = 0

MAX_SPEED = 4.5
MAX_REVERSE_SPEED = 2.5

ACCELERATION = 0.18
BRAKE = 0.22

FRICTION = 0.97

TURN_SPEED = 0.06

SENSOR_DISTANCE = 35
SENSOR_SIDE_ANGLE = math.radians(40)

SENSOR_DOT_RADIUS = 4
SHOW_HITBOX = False

REWARD_ALIVE = 0.02
REWARD_FORWARD_SPEED_SCALE = 0.015
REWARD_CRASH = -50.0

NEAT_MAX_SPEED = 3.5
NEAT_FRICTION = 0.96

NEAT_STEER_SCALE = 0.95
NEAT_REWARD_ALIVE = 0.003
NEAT_REWARD_FORWARD_SPEED_SCALE = 0.015
NEAT_REWARD_MOVEMENT_SCALE = 0.005
NEAT_REWARD_PROGRESS_BONUS = 0.0
NEAT_REWARD_CHECKPOINT_BONUS = 8.0
NEAT_REWARD_TO_CHECKPOINT_IMPROVEMENT = 0.10
NEAT_REWARD_TO_CHECKPOINT_BACKSLIDE = 0.05
NEAT_REWARD_CENTER_BONUS = 0.06
NEAT_CRASH_PENALTY = -20.0
NEAT_STALL_DEATH_PENALTY = -8.0

SHOW_NEAT_SENSOR_DEBUG = False
SHOW_NEAT_CHECKPOINT_DEBUG = False
